### ISSUE TITLE
Can this be modified to support accessing blobs with MSI?

### ISSUE THREAD

**Issue by sfc-gh-lrobles** [microsoft/fluent-plugin-azure-storage-append-blob#5]
In our environment, we do not want to generate "root level" SAS tokens.

Is there anyway this plugin can be modified to support using a "bearer" token obtained from the OAuth endpoint?

**Comment by logachev** [comment]
When we started working on this, MSI was not yet available.. Do you happen to know if ruby SDK supports it now?

**Comment by ds89snsadbf** [comment]
We ended up writing it ousrselves
